## Assignment_9
  - Data 파일을 이용한 Multinomial Classification
    * data_multinomial_classification.csv을 이용해 학습한다
      + 16개의 input, 1개의 output

$$ [x_{1},......x_{16},y] $$

  - Accuracy 95% 이상을 달성한다

In [ ]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as func
import torch.optim as opt
import io
import pandas as pd

torch.manual_seed(1)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
fileLocation = '/content/drive/MyDrive/Colab Notebooks/data_multinomial_classification.csv'
#드라이브에 업로드한 파일 위치

In [ ]:
rawData = pd.read_csv(fileLocation)
rawData.head()
#파일 불러오기

1  0  0.1  1.1  0.2  0.3  1.2  1.3  ...  1.5  0.4  0.5  4  0.6  0.7  1.6  0.8
0  1  0    0    1    0    0    0    1  ...    1    0    0  4    1    0    1    0
1  0  0    1    0    0    1    1    1  ...    0    0    1  0    1    0    0    3
2  1  0    0    1    0    0    1    1  ...    1    0    0  4    0    0    1    0
3  1  0    0    1    0    0    1    1  ...    1    0    0  4    1    0    1    0
4  1  0    0    1    0    0    0    1  ...    1    0    0  4    1    0    1    0

[5 rows x 17 columns]

In [ ]:
#feature_data = list(rawData.columns.values)
arrayData = rawData.values
print(arrayData)
print(np.shape(arrayData))
#print(feature_data)
#csv파일을 배열로 변환

[[1 0 0 ... 0 1 0]
 [0 0 1 ... 0 0 3]
 [1 0 0 ... 0 1 0]
 ...
 [1 0 0 ... 0 1 0]
 [0 0 1 ... 0 0 6]
 [0 1 1 ... 0 0 1]]
(100, 17)


In [ ]:
xData = arrayData[0 :, 0:16]

yData = arrayData[0 :, 16]

print(np.shape(xData))
print(np.shape(yData))
print(xData)
print(yData)
#xData, yData를 선언

(100, 16)
(100,)
[[1 0 0 ... 1 0 1]
 [0 0 1 ... 1 0 0]
 [1 0 0 ... 0 0 1]
 ...
 [1 0 0 ... 1 0 1]
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 1 0 0]]
[0 3 0 0 0 0 3 3 0 0 1 3 6 6 6 1 0 3 0 1 1 0 1 5 4 4 0 0 0 5 0 0 1 3 0 0 1
 3 5 5 1 5 1 0 0 6 0 0 0 0 5 4 6 0 0 1 1 1 1 3 3 2 0 0 0 0 0 0 0 0 1 6 3 0
 0 2 6 1 1 2 6 3 1 0 6 3 1 5 4 2 2 3 0 0 1 0 5 0 6 1]


In [ ]:
xData_T = torch.Tensor(xData)
yData_T = torch.LongTensor(yData)
print(np.shape(xData_T))
print(np.shape(yData_T))
print(yData_T)
#xData, yData를 tensor로 변환

torch.Size([100, 16])
torch.Size([100])
tensor([0, 3, 0, 0, 0, 0, 3, 3, 0, 0, 1, 3, 6, 6, 6, 1, 0, 3, 0, 1, 1, 0, 1, 5,
        4, 4, 0, 0, 0, 5, 0, 0, 1, 3, 0, 0, 1, 3, 5, 5, 1, 5, 1, 0, 0, 6, 0, 0,
        0, 0, 5, 4, 6, 0, 0, 1, 1, 1, 1, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 6,
        3, 0, 0, 2, 6, 1, 1, 2, 6, 3, 1, 0, 6, 3, 1, 5, 4, 2, 2, 3, 0, 0, 1, 0,
        5, 0, 6, 1])


In [ ]:
model =nn.Linear(16, 7)

In [ ]:
optimizer = opt.SGD(model.parameters(), lr=0.1)

for epoch in range(1000):
  Y_ANS = model(xData_T)
  cost = func.cross_entropy(Y_ANS, yData_T)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 99:
    prediction = Y_ANS.argmax(dim=1) == yData_T
    accuracy = prediction.sum().item() / len(prediction)
    print('Epoch {:4d}/{} Cost: {: 6f} Accuracy {:2.2f}%'. format(epoch, 1000, cost.item(), accuracy * 100))

Epoch   99/1000 Cost:  0.467067 Accuracy 86.00%
Epoch  199/1000 Cost:  0.322138 Accuracy 93.00%
Epoch  299/1000 Cost:  0.250965 Accuracy 95.00%
Epoch  399/1000 Cost:  0.206627 Accuracy 95.00%
Epoch  499/1000 Cost:  0.175908 Accuracy 96.00%
Epoch  599/1000 Cost:  0.153229 Accuracy 99.00%
Epoch  699/1000 Cost:  0.135753 Accuracy 100.00%
Epoch  799/1000 Cost:  0.121860 Accuracy 100.00%
Epoch  899/1000 Cost:  0.110548 Accuracy 100.00%
Epoch  999/1000 Cost:  0.101160 Accuracy 100.00%
